[package]
name = "sharp"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
name = "sharp"
path = "src/lib.rs"

[dependencies]
#rs-vips = {path="../rs-vips"}
rs-vips = { git = "https://github.com/mrdkprj/rs-vips.git", rev="396779810a4d99722442c99c2fa64c84dc60f429" }
serde = { version = "1.0", features = ["derive"] }
num-traits = "0.2"
num-derive = "0.4"
strum = "0.27"
strum_macros = "0.27"
async-std = "1.13.1"

[profile.release]
opt-level = "s"
debug = false
strip = "none"
debug-assertions = false
overflow-checks = false
lto = true
panic = 'unwind'
incremental = false
codegen-units = 1
rpath = false
